packages:
  - "."

overrides:
  vite: 6.3.5

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - ffmpeg-static
  - sharp

allowBuilds:
  "@tailwindcss/oxide": true
  esbuild: true
  ffmpeg-static: true
  sharp: true
